stages:
  train:
    params:
      - params.yaml:
          - train
    deps:
      - train.py
    cmd: python train.py --params params.yaml
    outs:
      - runs/train/weights/last.pt:
          checkpoint: true
      - runs/train/weights/best.pt:
          checkpoint: true
      - runs/train/labels_correlogram.jpg
      - runs/train/labels.jpg
      - runs/train/train_batch0.jpg
      - runs/train/confusion_matrix.png
      - runs/train/results.png
    metrics:
      - runs/train/results.txt:
          cache: false
      - runs/train/hyp.yaml:
          cache: false
  # TODO: should it be here? And detect/export/hubconf stages?
  # SHould they be tracked with dvc? -- Just in dvc, not in pipelines, probably
  test:
    params:
      - params.yaml:
          - test
    deps: 
      - test.py
      - ${test.weights}
    # TODO: add weights from the last stage and other params
    cmd: python test.py --params params.yaml
    outs:
      # TODO: optional outputs are commented, cause pipeline fails when they are not created
      # see https://github.com/iterative/dvc/issues/4410
      # - runs/test/F1_curve.png
      # - runs/test/P_curve.png
      - runs/test/confusion_matrix.png
      - runs/test/test_batch0_pred.jpg
      # - runs/test/PR_curve.png
      # - runs/test/R_curve.png
      - runs/test/test_batch0_labels.jpg
  detect:
    params:
      - params.yaml:
          - detect
    deps:
      - detect.py
      - ${detect.weights}
    cmd: python detect.py --params params.yaml
    outs:
      # should we track runs/detect folder instead of separate pictures?
      - runs/detect/bus.jpg
      - runs/detect/zidane.jpg
  export:
    params:
      - params.yaml:
          - export
    deps:
      - models/export.py
      - ${export.weights}
    cmd: python models/export.py --weights ${export.weights}
    outs:
      - runs/train/weights/best.torchscript.pt
      - runs/train/weights/best.onnx
      - runs/train/weights/best.mlmodel
  # hubconf:
  #   deps:
  #     - hubconf.py
  #   cmd: python hubconf.py
  #   outs:
  #     - runs/hub/bus.jpg
  #     - runs/hub/image2.jpg
  #     - runs/hub/image4.jpg
  #     - runs/hub/zidane.jpg
