name: CI CPU testing

on:  # https://help.github.com/en/actions/reference/events-that-trigger-workflows
  push:
    branches: [ dvc ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ dvc ]
  # schedule:
  #   - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  cpu-tests:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # MacOS and windows require the different yq installation
        os: [ubuntu-latest]  #, macos-latest, windows-latest]
        python-version: [3.8]
        model: ['yolov5s']  # models to test

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Note: This uses an internal pip API and may not always work
      # https://github.com/actions/cache/blob/master/examples.md#multiple-oss-in-a-workflow
      - name: Get pip cache
        id: pip-cache
        run: |
          python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"

      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-

      - name: Install dependencies
        run: |
          # yq
          sudo wget -q https://github.com/mikefarah/yq/releases/download/v4.9.4/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          # python deps
          python -m pip install --upgrade pip
          pip install -qr requirements.txt -f https://download.pytorch.org/whl/cpu/torch_stable.html
          python --version
          pip --version
          pip list
        shell: bash

      - name: Tests workflow
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          DEFAULT_BRANCH: dvc
        run: |
          set -x
          # export PYTHONPATH="$PWD"  # to run '$ python *.py' files in subdirectories
          di=cpu # inference devices  # define device

          # # uncomment this to check that .py scripts work
          # # train
          # python train.py --params params-test-end2end.yaml

          # # detect
          # python detect.py --params params-test-scripts.yaml
          # python detect.py --params params-test-end2end.yaml

          # # test
          # python test.py --params params-test-scripts.yaml
          # python test.py --params params-test-end2end.yaml

          # test that dvc pipelines work and scripts work from train to export
          yq eval-all '. as $item ireduce ({}; . * $item )' params-default.yaml tests/extra-params-end2end.yaml > params.yaml
          dvc repro

          python hubconf.py  # hub
          python models/yolo.py --cfg models/${{ matrix.model }}.yaml  # inspect

          # test that dvc pipelines work and scripts work against some proven models weights
          yq eval-all '. as $item ireduce ({}; . * $item )' params-default.yaml tests/extra-params-scripts.yaml > params.yaml
          # TODO: the weights now are stored in default branch, may be better to move somewhere
          dvc get $GITHUB_SERVER_URL/$GITHUB_REPOSITORY --rev $DEFAULT_BRANCH yolov5s.pt
          dvc repro detect test export

        shell: bash
